# This is a config for E2B sandbox template.
# You can use template ID (ge2m9qna4f7277wqtzob) or template name (evoke-nextjs-test-1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("evoke-nextjs-test-1") # Sync sandbox
# sandbox = await AsyncSandbox.create("evoke-nextjs-test-1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('evoke-nextjs-test-1')

start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "evoke-nextjs-test-1"
template_id = "ge2m9qna4f7277wqtzob"
